image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Claude Coder
    command: |
      echo "🛠️ Setting up Claude Coder extension..."
      code --install-extension kodu-ai.claude-coder

vscode:
  extensions:
    - kodu-ai.claude-coder

ports:
  - port: 3000
    onOpen: open-preview

gitpod:
  startupTasks:
    - command: |
        echo "✅ Ready to code with Claude Coder!"